### ISSUE TITLE
A Tribute page using html and css 

### ISSUE THREAD

**Issue by stoody-dev** [abhimanyuiscoding/Hacktoberfest2022#138]
please assign this issue to me under hacktoberfest2022 tag

**Comment by stoody-dev** [comment]
please assign this to me

**Comment by nimeshika06** [comment]
@abhimanyuiscoding please assign the issue to me under hacktoberfest 2022

**Comment by CHIRAG137** [comment]
@abhimanyuiscoding can you please assign this issue to me under hacktoberfest2022 tag!!!!!!
</happy coding>

**Comment by yashvardhansingh15** [comment]
@abhimanyuiscoding  can you please assign me

**Comment by muskandn** [comment]
I would be grateful if you give me the opportunity to resolve this issue.

**Comment by SharmilaChoudhary** [comment]
These are the links of my previous work where i have used html and css
(https://github.com/SharmilaChoudhary/simon-game 
https://github.com/SharmilaChoudhary/NFTMARKETPLACE)

If you give me this opportunity I believe I can do a great job at it

**Comment by Sonali314** [comment]
kindly assign me this work
