### ISSUE TITLE
Palindrome No in C++

### ISSUE THREAD

**Issue by BTANISHA11** [abhimanyuiscoding/Hacktoberfest2022#143]
### Add Palindrome No. in C++
I want to add program for checking whether a number is palindrome or not.
can you pls assign this to me @abhimanyuiscoding

**Comment by kushagrarastogi7007** [comment]
I want to add program of palindrome no., pls assign me this @abhimanyuiscoding

**Comment by abhayanand08** [comment]
@abhimanyuiscoding  I want to add a short solution for this task . Can you please kindly assign me this task.

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by abhayanand08** [comment]
@abhimanyuiscoding I want to add a short solution for this task . Can you please kindly assign me this task.

**Comment by abhayanand08** [comment]
@abhimanyuiscoding please assign this to me. I want to contribute to this issue with the efficient approach.

**Comment by Ankita-278** [comment]
Can you pls assign me this issue?

**Comment by nisthajnn** [comment]
please assign this to me

**Comment by BTANISHA11** [comment]
I have added this 
pls add hacktober fest label to it
